"""add_programs_column

Revision ID: 963cb668e785
Revises: b75093306f49
Create Date: 2026-06-25 08:12:43.634416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '963cb668e785'
down_revision: Union[str, Sequence[str], None] = 'b75093306f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('programs', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'programs')
    # ### end Alembic commands ###
