"""add_hints_and_similar_questions

Revision ID: b75093306f49
Revises: 6684f52e0422
Create Date: 2026-06-25 07:45:53.320171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b75093306f49'
down_revision: Union[str, Sequence[str], None] = '6684f52e0422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('hints', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('problems', sa.Column('similar_questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'similar_questions')
    op.drop_column('problems', 'hints')
    # ### end Alembic commands ###
